<?php
return [
    'roleNames' => [
        'Advokatas',
        'Gydytojas',
        'Inžinierius',
        'Lakūnas',
        'Mechanikas',
        'Mokytojas',
        'Policininkas',
        'Sekretorius',
        'Slaugytojas',
        'Vadybininkas',
        'Vairuotojas',
        'Valytojas',
    ],
    'roleFull' => [
        [
            'salary' => 7500,
            'taxes' => 1830,
            'flat_payment' => 1100,
            'study_payment' => 390,
            'car_payment' => 220,
            'credit_payment' => 180,
            'loan_payment' => 50,
            'extra_expenses' => 1650,
            'child_expenses' => 380,
            'flat_loan' => 115000,
            'study_loan' => 78000,
            'car_loan' => 11000,
            'credit_loan' => 6000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 13200,
            'taxes' => 3420,
            'flat_payment' => 1900,
            'study_payment' => 750,
            'car_payment' => 380,
            'credit_payment' => 270,
            'loan_payment' => 50,
            'extra_expenses' => 2880,
            'child_expenses' => 640,
            'flat_loan' => 202000,
            'study_loan' => 150000,
            'car_loan' => 19000,
            'credit_loan' => 9000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 4900,
            'taxes' => 1050,
            'flat_payment' => 700,
            'study_payment' => 60,
            'car_payment' => 140,
            'credit_payment' => 120,
            'loan_payment' => 50,
            'extra_expenses' => 1090,
            'child_expenses' => 250,
            'flat_loan' => 75000,
            'study_loan' => 12000,
            'car_loan' => 7000,
            'credit_loan' => 4000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 9500,
            'taxes' => 2350,
            'flat_payment' => 1330,
            'study_payment' => 0,
            'car_payment' => 300,
            'credit_payment' => 660,
            'loan_payment' => 50,
            'extra_expenses' => 2210,
            'child_expenses' => 480,
            'flat_loan' => 143000,
            'study_loan' => 0,
            'car_loan' => 15000,
            'credit_loan' => 22000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 2000,
            'taxes' => 360,
            'flat_payment' => 300,
            'study_payment' => 0,
            'car_payment' => 60,
            'credit_payment' => 60,
            'loan_payment' => 50,
            'extra_expenses' => 450,
            'child_expenses' => 110,
            'flat_loan' => 31000,
            'study_loan' => 0,
            'car_loan' => 3000,
            'credit_loan' => 2000,
            'loan' => 1000,
            'cash' => 670,
        ],
        [
            'salary' => 3300,
            'taxes' => 630,
            'flat_payment' => 500,
            'study_payment' => 60,
            'car_payment' => 100,
            'credit_payment' => 90,
            'loan_payment' => 50,
            'extra_expenses' => 760,
            'child_expenses' => 180,
            'flat_loan' => 50000,
            'study_loan' => 12000,
            'car_loan' => 5000,
            'credit_loan' => 3000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 3000,
            'taxes' => 580,
            'flat_payment' => 400,
            'study_payment' => 0,
            'car_payment' => 100,
            'credit_payment' => 60,
            'loan_payment' => 50,
            'extra_expenses' => 690,
            'child_expenses' => 160,
            'flat_loan' => 46000,
            'study_loan' => 0,
            'car_loan' => 5000,
            'credit_loan' => 2000,
            'loan' => 1000,
            'cash' => 520,
        ],
        [
            'salary' => 2500,
            'taxes' => 460,
            'flat_payment' => 400,
            'study_payment' => 0,
            'car_payment' => 80,
            'credit_payment' => 60,
            'loan_payment' => 50,
            'extra_expenses' => 570,
            'child_expenses' => 140,
            'flat_loan' => 38000,
            'study_loan' => 0,
            'car_loan' => 4000,
            'credit_loan' => 2000,
            'loan' => 1000,
            'cash' => 710,
        ],
        [
            'salary' => 3100,
            'taxes' => 600,
            'flat_payment' => 400,
            'study_payment' => 30,
            'car_payment' => 100,
            'credit_payment' => 90,
            'loan_payment' => 50,
            'extra_expenses' => 710,
            'child_expenses' => 170,
            'flat_loan' => 47000,
            'study_loan' => 6000,
            'car_loan' => 5000,
            'credit_loan' => 3000,
            'loan' => 1000,
            'cash' => 480,
        ],
        [
            'salary' => 4600,
            'taxes' => 910,
            'flat_payment' => 700,
            'study_payment' => 60,
            'car_payment' => 120,
            'credit_payment' => 90,
            'loan_payment' => 50,
            'extra_expenses' => 1000,
            'child_expenses' => 240,
            'flat_loan' => 75000,
            'study_loan' => 12000,
            'car_loan' => 6000,
            'credit_loan' => 3000,
            'loan' => 1000,
            'cash' => 400,
        ],
        [
            'salary' => 2500,
            'taxes' => 460,
            'flat_payment' => 400,
            'study_payment' => 0,
            'car_payment' => 80,
            'credit_payment' => 60,
            'loan_payment' => 50,
            'extra_expenses' => 570,
            'child_expenses' => 140,
            'flat_loan' => 38000,
            'study_loan' => 0,
            'car_loan' => 4000,
            'credit_loan' => 2000,
            'loan' => 1000,
            'cash' => 750,
        ],
        [
            'salary' => 1600,
            'taxes' => 280,
            'flat_payment' => 200,
            'study_payment' => 0,
            'car_payment' => 60,
            'credit_payment' => 60,
            'loan_payment' => 50,
            'extra_expenses' => 300,
            'child_expenses' => 70,
            'flat_loan' => 20000,
            'study_loan' => 0,
            'car_loan' => 4000,
            'credit_loan' => 2000,
            'loan' => 1000,
            'cash' => 560,
        ],
    ],
];
